Removed the non-C99 version of FOREACH, since it does not work anyway if the same iterator variable is used twice.
Correspond to this bug if in C89 (ANSI) mode:
/home/keryell/projets/PIPS/MYPIPS/prod/pips/src/Libs/ricedg/ricedg.c: In function 'loop_variant_list':
/home/keryell/projets/PIPS/MYPIPS/prod/pips/src/Libs/ricedg/ricedg.c:2508: error: redeclaration of 'v' with no linkage
/home/keryell/projets/PIPS/MYPIPS/prod/pips/src/Libs/ricedg/ricedg.c:2503: error: previous declaration of 'v' was here

Conclusion: we are in 2009, use C99! :-)


git-svn-id: http://svn.cri.ensmp.fr/svn/newgen/trunk@1054 80f2d23d-f6f1-0310-8ea7-b0e6515bd809